services:
  - type: web
    name: flappy-bird-api
    runtime: java
    buildCommand: cd api && mvn clean install
    startCommand: cd api && java -jar target/flappy-bird-api-1.0.0.jar
    env: java
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: flappybird-db
          property: connectionString
      - key: DATABASE_DRIVER
        value: org.postgresql.Driver
      - key: DATABASE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

databases:
  - name: flappybird-db
    databaseName: flappybird
    user: flappybird
